image: python:3.8-buster

before_script:
  - pip install mkdocs
  - pip install mkdocs-material

pages:
  stage: deploy
  script:
    - mkdocs build --verbose
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
