site_name: Flutter для ОС Аврора
site_dir: public
site_url: https://omprussia.gitlab.io/flutter/flutter
repo_url: https://gitlab.com/omprussia/flutter
site_description: >-
  Flutter SDK с поддержкой платформы ОС Аврора для создания приложений Flutter.

# Navigation
nav:
  - Главная:
      - Index: index.md
      - Flutter Links:
          - SDK: https://gitlab.com/omprussia/flutter/flutter
          - Embedder: https://gitlab.com/omprussia/flutter/flutter-embedder
          - Plugins: https://gitlab.com/omprussia/flutter/flutter-plugins
          - Engine: https://gitlab.com/omprussia/flutter/flutter-engine
      - Community Links:
          - Telegram: https://t.me/aurora_devs/23477
  - О проекте:
      - Платформа ОС Аврора: structure/platform.md
      - Компоненты: structure/components.md
      - Плагины: structure/plugins.md
  - Установка:
      - Linux: install/linux.md
      - Windows: install/windows.md
  - Примеры:
      - Hello, World!: examples/build.md
      - Плагин D-Bus: examples/dbus.md
      - Плагин FFI: examples/ffi.md
      - Плагин Platform: examples/platform-channels.md
      - Плагин Platform & Qt: examples/platform-channels-qt.md
  - Поддержка:
      - Index: support/index.md
      - Flutter CLI: support/cli.md
      - Плагины ОМП: support/omp.md
      - Сторонние плагины: support/community.md
      - Сторонние инструменты: support/tools.md
  - Публикации:
      - Статьи: publication/articles.md
      - Видео: publication/video.md
  - FAQ: faq/index.md

# Assets
extra_css:
  - assets/css/main.css

# Extensions
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Configuration
theme:
  name: 'material'
  language: 'ru'
  custom_dir: docs/assets
  favicon: images/favicon.ico
  template: home.html
  icon:
    logo: custom/icon
  features:
    - toc.integrate
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
